# Generated by Django 4.0 on 2022-01-03 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_auto_20211221_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('stock', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('categoria', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Cremas',
        ),
        migrations.DeleteModel(
            name='Labiales',
        ),
    ]
