# Generated by Django 4.0 on 2022-01-03 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_rename_categorias_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='URLimagen',
            field=models.CharField(default='', max_length=160),
            preserve_default=False,
        ),
    ]
