# Generated by Django 4.0 on 2022-01-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0006_producto_urlimagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default='Sin descripcion'),
            preserve_default=False,
        ),
    ]
